# https://github.com/dephraiim/translate-readme
name: Translate README

on:
  push:
    branches:
      - main
    paths:
      - README.md
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      # ISO Langusge Codes: https://cloud.google.com/translate/docs/languages
      - name: Adding README - Chinese Simplified
        uses: dephraiim/translate-readme@main
        with:
          LANG: zh-CN
      # - name: Adding README - Chinese Traditional
      #   uses: dephraiim/translate-readme@main
      #   with:
      #     LANG: zh-TW
      # - name: Adding README - Hindi
      #   uses: dephraiim/translate-readme@main
      #   with:
      #     LANG: hi
      # - name: Adding README - Arabic
      #   uses: dephraiim/translate-readme@main
      #   with:
      #     LANG: ar
      # - name: Adding README - French
      #   uses: dephraiim/translate-readme@main
      #   with:
      #     LANG: fr
